import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/my_theme";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/modal-provider";
const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord Clone Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(
          font.className,
          "bg-white dark:bg-[#313338]")}>
            <ThemeProvider 
              attribute="class" 
              defaultTheme="dark" 
              enableSystem={false} 
              storageKey="discord-theme"
            >
              <ModalProvider></ModalProvider>
                {children}
            </ThemeProvider>
        </body>
      </html>
    </>
  );
}
